<!-- Label the page -->
<div class="page-header">
    <h2>Comparison of Solar Production</h2>
</div>

<div class="row">
	<div class="col-md-12">
		<p>
			Below is a chart showing the amount of electricity generated by the
			solar panels in the different locations with active metering. The
			graph is stacked, meaning each bar represents the total amount
			generated by all sites for the month.
		</p>
	</div><!--/.col-md-12 -->
</div><!--/.row -->

<div class="row">
    <div class="col-md-8">
        <div class="row">
            <h3 id="yearlyTitle" class="text-center"></h3>
            <div id="dvYearlyChart" class="chart"></div>
            <div id="dvYearlyChartLegend" class="chart-legend chart-legend-lower"></div>
        </div>
        <div class="row">
            <p>&nbsp;</p>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <button id="btnPrevYearly" type="button" class="btn btn-default pull-left">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    Previous Year
                </button>
            </div><!--/.col-md-6 col-xs-12 -->
            <div class="col-md-6 col-xs-12">
                <button id="btnNextYearly" type="button" class="btn btn-default pull-right disabled">
                    Next Year
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </button>
            </div><!--/.col-md-6 col-xs-12 -->
        </div>
    </div><!--/.col-md-8 -->
    <div class="col-md-4">
    	<div class="col-sm-12">
            <h3>Data Source</h3>
            <p class='chart-sizer'>
                <a href='https://www.enphase.com/'><img src='http://statics.solar.ypsi.com/images/enphase_logo.png' alt='Enphase Energy' /></a>
            </p>
        </div><!--/.col-sm-12 -->
    </div><!--/.col-md-4 -->
</div><!--/.row -->